DataCollection:
    name:
        Vegetation Phenology and Productivity Parameters Season 1 Yearly
    api_id:
        byoc-67c73156-095d-4f53-8a09-9ddf3848fbb6
    catalog_id:
        67c73156-095d-4f53-8a09-9ddf3848fbb6
    service_url:
        https://creodias.sentinel-hub.com
    is_timeless:
        False
Output:
    mosaicking_order: null
    frequency: 'yearly'
    resolution: 100
