DataCollection:
    name:
        Water Bodies
    api_id:
        byoc-62bf6f6a-c584-48a8-a739-0bc60efee54a
    catalog_id:
        62bf6f6a-c584-48a8-a739-0bc60efee54a
    service_url:
        https://creodias.sentinel-hub.com
    is_timeless:
        False
Output:
    mosaicking_order: null
    frequency: 'monthly'
    resolution: 10
