DataCollection:
    name:
        Vegetation Indices Daily
    api_id:
        byoc-90f0abac-87cf-4277-958b-d8c56d9e5371
    catalog_id:
        90f0abac-87cf-4277-958b-d8c56d9e5371
    service_url:
        https://creodias.sentinel-hub.com
    is_timeless:
        False
Output:
    mosaicking_order: null
    frequency: 'yearly'
    resolution: 10
