# Rename this file config_eo_service.yml and add the credentials, below.

creodias:
    priority: 5 # Lower value means lower priority (Default: 0)
    search:   # Search parameters configuration
    download:
        extract:
        outputs_prefix: /data/
    auth:
        credentials:
            username:
            password:
    storage:
        region_name: null
        endpoint_url_local: http://data.cloudferro.com
        endpoint_url_ext: https://cf2.cloudferro.com:8080
        aws_access_key_id:
        aws_secret_access_key:
        config: null
        output_directory: /data/
        bucket:
sentinel-hub:
    instance_id: $SH_INSTANCE_ID
    sh_client_id: $SH_CLIENT_ID
    sh_client_secret: $SH_CLIENT_SECRET
