DataCollection:
    name:
        Global Water Bodies
    api_id:
        byoc-9a525f12-33b6-424e-a0f2-d567eec0f277
    catalog_id:
        9a525f12-33b6-424e-a0f2-d567eec0f277
    service_url:
        https://creodias.sentinel-hub.com
    is_timeless:
        False
Output:
    mosaicking_order: null
    frequency: 'yearly'
    resolution: 10
