DataCollection:
    name:
        CORINE Land Cover Accounting Layer
    api_id:
        byoc-4c5441a6-6040-4dc4-a392-c1317bbd1031
    catalog_id:
        4c5441a6-6040-4dc4-a392-c1317bbd1031
    service_url:
        https://creodias.sentinel-hub.com
    is_timeless:
        False
Output:
    mosaicking_order: null
    frequency: 'yearly'
    resolution: 100
