DataCollection:
    name:
        Global Land Cover
    api_id:
        byoc-f0a97620-0e88-4c1f-a1ac-bb388fabdf2c
    catalog_id:
        f0a97620-0e88-4c1f-a1ac-bb388fabdf2c
    service_url:
        https://creodias.sentinel-hub.com
    is_timeless:
        False
