DataCollection:
    name:
        Vegetation Indices Daily
    api_id:
        byoc-472c0398-430d-4157-a62d-603363d7a4e8
    catalog_id:
        472c0398-430d-4157-a62d-603363d7a4e8
    service_url:
        https://creodias.sentinel-hub.com
    is_timeless:
        False
Output:
    mosaicking_order: null
    frequency: 'daily'
    resolution: 10
